@startuml Diagrama

class Producto {
    - modelo 
    - descripcion
    - marca
    - tipo
    - codigo
}

class Accesorio 

class Arma {
    - calibre
}

class Municion {
    - calibre
    - cantidad
}

class Persona{
    - nombre
    - apeellido
    - direccion
    - contacto
    - email
}

class Cliente {
    - codigo_de_cliente
}

class Proveedor {
    - codigo_de_proveedor
}

Producto -- Accesorio
Producto -- Arma
Producto -- Municion

Persona -- Cliente
Persona -- Proveedor

@enduml