"""empty message

Revision ID: 82f882ba90d1
Revises: 
Create Date: 2023-09-07 17:20:57.463528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82f882ba90d1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('_Client__id', sa.Integer(), nullable=False),
    sa.Column('_Client__name', sa.String(length=250), nullable=True),
    sa.Column('_Client__dni', sa.String(length=250), nullable=True),
    sa.Column('_Client__client_code', sa.String(length=250), nullable=True),
    sa.Column('_Client__address', sa.String(length=250), nullable=True),
    sa.Column('_Client__email', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('_Client__id')
    )
    op.create_table('product_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.Column('caliber', sa.String(length=250), nullable=True),
    sa.Column('brand', sa.String(length=250), nullable=True),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.Column('type', sa.String(length=250), nullable=True),
    sa.Column('serial_number', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('supplier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cuil', sa.String(length=250), nullable=True),
    sa.Column('email', sa.String(length=250), nullable=True),
    sa.Column('code', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('supplier')
    op.drop_table('products')
    op.drop_table('product_type')
    op.drop_table('clients')
    # ### end Alembic commands ###
